GET http://localhost:8000/api/v1/characters

###

GET http://localhost:8000/api/v1/characters/666f0bb31f3eaebb6ceb719f

###
POST http://localhost:8000/api/v1/characters
Content-Type: application/json

{
    "name": "Minato",
    "age": 22,
    "village": "Leaf Villiage"
}

###
PATCH http://localhost:8000/api/v1/characters/666f0bb31f3eaebb6ceb719f
Content-Type: application/json

{
    "name": "Lee",
    "age": 17,
    "villiage": "Leaf Villiage"
}

###

DELETE http://localhost:8000/api/v1/characters/666f0bb31f3eaebb6ceb719f

###